version: 2

sources:
  - name: silver
    database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
    schema: "{{ env_var('SNOWFLAKE_SCHEMA', 'ECOMMERCE') }}"
    tables:
      - name: SILVER_ORDERS
        description: "cleaned orders from the silver layer"
        columns:
          - name: ORDER_ID
            tests:
              - not_null
              - unique
          - name: CUSTOMER_ID
            tests:
              - not_null
          - name: TOTAL_AMOUNT
            tests:
              - not_null
